baselines
baseline: spec
	<baseline>
	
	spec baseline: 'ZincHTTPComponents' with: [ spec repository: 'github://svenvc/zinc/repository' ].
	
	spec baseline: 'NeoJSON' with: [ spec repository: 'github://svenvc/NeoJSON/repository' ].
	
	spec baseline: 'Mocketry' with: [ spec repository: 'github://dionisiydk/Mocketry' ].
	
	spec baseline: 'PetitParser2Core' with: [ spec repository: 'github://kursjan/petitparser2' ]